import { useAuthState } from "react-firebase-hooks/auth";
import Head from "next/head";
import { auth } from "@/firebase/clientApp";
import { User, signOut } from "firebase/auth";
import ConfirmTable from "@/components/admin/ConfirmTable";
import Login from "@/components/admin/Login";
import { useStateContext } from "@/lib/context";
import { Box, Button, Flex, Icon, Text } from "@chakra-ui/react";
import { useState } from "react";

export default function Home() {
  const [user] = useAuthState(auth);
  const { showConfirmedOrders, showPendingOrders, orderToConfirm } =
    useStateContext();
  const logout = async () => {
    await signOut(auth);
  };
  return (
    <>
      <Head>
        <title>Aara Co Uniforms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/logo.jpg" />
      </Head>

      <Flex mt="90px" direction="column">
        {!user ? (
          <Flex align="center" justify="center" direction="column">
            <Login />
          </Flex>
        ) : (
          <>
            <Flex width="80%" margin="0px auto" direction="column">
              <Text fontWeight={600} align="center" mt={2}>
                Select an order to view it&apos;s details
              </Text>
            </Flex>
          </>
        )}
      </Flex>

      {orderToConfirm.user != null ? <ConfirmTable /> : ""}

      {user && (
        <Flex
          zIndex={showConfirmedOrders | showPendingOrders ? -1 : 999}
          bg="orange.200"
          width="100%"
          p={2}
          bottom="0"
          position={"fixed"}
          mt="20%"
          // zIndex={999}
          align="center"
          justify="center"
        >
          <Text
            transition="0.4s"
            cursor="pointer"
            onClick={() => logout()}
            _hover={{ transform: "translateY(-5px)" }}
          >
            sign out
          </Text>
        </Flex>
      )}
    </>
  );
}
