import Head from "next/head";
import { LKGUKGData } from "@/data/LKGUKG";
import Item from "@/components/Item";
import { Box } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box mt="90px">
        <select placeholder="Select Child">
          <option>Select Child</option>
        </select>
        <Box mt={2} width="100%">
          {LKGUKGData.map((item, index) => (
            <>
              <Item item={item} />
            </>
          ))}
        </Box>
      </Box>
    </>
  );
}
